# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/jorisroovers/gitlint
  rev: v0.19.1
  hooks:
  - id: gitlint

- repo: https://github.com/kynan/nbstripout
  rev: 0.7.1
  hooks:
    - id: nbstripout

- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.9.0
  hooks:
    - id: nbqa-autopep8
      args: [--ignore=E402]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks: # general hooks
    -   id: check-added-large-files
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-xml
    -   id: check-yaml

-   repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks: # documentation checker
    -   id: interrogate
        args: [--fail-under=80, -vv]

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.6.9
  hooks:
    # Run the linter.
    - id: ruff
      types_or: [ python, pyi, jupyter ]
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi, jupyter ]

- repo: https://github.com/astral-sh/uv-pre-commit
  # uv version.
  rev: 0.4.29
  hooks:
    # Update the uv lockfile
    - id: uv-lock
