name: Enforcing Conventional Commit Format

on:
    - pull_request

jobs:
  gitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install GitLint
        run: |
          python -m pip install gitlint

      - name: Run GitLint
        run: |
          gitlint --commits ${{ github.sha }}
        continue-on-error: ${{ github.event_name == 'pull_request' }}

      - name: Lint Pull Request Title
        if: github.event_name == 'pull_request'
        uses: jef/conventional-commits-pr-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
