name: Security Linting

on:
    - pull_request
jobs:
    trufflehog:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - uses: trufflesecurity/trufflehog@main

    bandit: 
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - uses: mdegis/bandit-action@v1.0
          with:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
